[package]
name = "simple-life"
version = "0.4.0"
edition = "2021"
description = "Simple async lifecycle trait and convenient macros"
license = "MIT"

[dependencies]
async-trait = "^0"
tokio = { version = "^1", features = ["sync", "time", "rt", "macros", "signal"] }
