[package]
name = "simple-life"
version = "0.1.1"
edition = "2021"
description = "Simple async lifecycle trait and convenient macros"
license="MIT"

[dependencies]
async-trait = "0.1.56"

[features]
tracing = []